<?php

/**
 * Materials Direct - Price Generation Error Diagnostics
 *
 * Creates a small diagnostic table and provides an AJAX endpoint
 * for recording failed calculate_secure_price requests.
 *
 * This code does NOT modify the pricing calculation itself.
 */


/* ============================================================
 * 1. CREATE DIAGNOSTIC DATABASE TABLE
 * ============================================================ */

function md_create_price_diagnostics_table() {

    global $wpdb;

    $table_name = $wpdb->prefix . 'md_price_diagnostics';

    // Only create the table if it does not already exist.
    if ($wpdb->get_var($wpdb->prepare(
        "SHOW TABLES LIKE %s",
        $table_name
    )) === $table_name) {
        return;
    }

    require_once ABSPATH . 'wp-admin/includes/upgrade.php';

    $charset_collate = $wpdb->get_charset_collate();

    $sql = "CREATE TABLE {$table_name} (
        id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
        incident_reference varchar(50) NOT NULL,
        created_at datetime NOT NULL,
        http_status int(10) unsigned NOT NULL DEFAULT 0,
        http_status_text varchar(100) NOT NULL DEFAULT '',
        jquery_status varchar(100) NOT NULL DEFAULT '',
        error_thrown varchar(255) NOT NULL DEFAULT '',
        ajax_action varchar(100) NOT NULL DEFAULT '',
        ajax_url varchar(255) NOT NULL DEFAULT '',
        product_id bigint(20) unsigned NOT NULL DEFAULT 0,
        width decimal(20,6) NULL,
        length decimal(20,6) NULL,
        qty int(10) unsigned NOT NULL DEFAULT 0,
        discount_rate decimal(10,6) NULL,
        shape_type varchar(100) NOT NULL DEFAULT '',
        user_agent text NULL,
        PRIMARY KEY (id),
        UNIQUE KEY incident_reference (incident_reference),
        KEY created_at (created_at),
        KEY product_id (product_id),
        KEY http_status (http_status)
    ) {$charset_collate};";

    dbDelta($sql);
}


/*
 * Create the table when WordPress is loaded.
 *
 * The function checks whether the table exists before doing
 * anything, so this does not recreate the table on every request.
 */
add_action('init', 'md_create_price_diagnostics_table');


/* ============================================================
 * 2. AJAX ENDPOINT FOR RECORDING PRICE ERRORS
 * ============================================================ */

add_action(
    'wp_ajax_md_log_price_error',
    'md_log_price_error_callback'
);

add_action(
    'wp_ajax_nopriv_md_log_price_error',
    'md_log_price_error_callback'
);


function md_log_price_error_callback() {

    /*
     * Verify the same nonce used by the pricing AJAX system.
     *
     * This means we do not need to introduce another nonce
     * into your existing JavaScript localisation.
     */
    check_ajax_referer('custom_price_nonce', 'nonce');


    global $wpdb;

    $table_name = $wpdb->prefix . 'md_price_diagnostics';


    /* --------------------------------------------------------
     * Sanitize / validate incoming values
     * -------------------------------------------------------- */

    $incident_reference = isset($_POST['incident_reference'])
        ? sanitize_text_field(wp_unslash($_POST['incident_reference']))
        : '';

    if ($incident_reference === '') {
        wp_send_json_error([
            'message' => 'Missing incident reference.'
        ]);
    }


    /*
     * Make sure the reference has the format generated by
     * our JavaScript.
     *
     * Example:
     * PRICE-20260903135712-4821
     */
    if (!preg_match(
        '/^PRICE-[0-9]{14}-[0-9]{4}$/',
        $incident_reference
    )) {
        wp_send_json_error([
            'message' => 'Invalid incident reference.'
        ]);
    }


    $http_status = isset($_POST['http_status'])
        ? absint($_POST['http_status'])
        : 0;

    $http_status_text = isset($_POST['http_status_text'])
        ? sanitize_text_field(wp_unslash($_POST['http_status_text']))
        : '';

    $jquery_status = isset($_POST['jquery_status'])
        ? sanitize_text_field(wp_unslash($_POST['jquery_status']))
        : '';

    $error_thrown = isset($_POST['error_thrown'])
        ? sanitize_text_field(wp_unslash($_POST['error_thrown']))
        : '';

    $ajax_action = isset($_POST['ajax_action'])
        ? sanitize_text_field(wp_unslash($_POST['ajax_action']))
        : '';

    $ajax_url = isset($_POST['ajax_url'])
        ? esc_url_raw(wp_unslash($_POST['ajax_url']))
        : '';

    $product_id = isset($_POST['product_id'])
        ? absint($_POST['product_id'])
        : 0;

    $width = isset($_POST['width'])
        ? (float) $_POST['width']
        : null;

    $length = isset($_POST['length'])
        ? (float) $_POST['length']
        : null;

    $qty = isset($_POST['qty'])
        ? absint($_POST['qty'])
        : 0;

    $discount_rate = isset($_POST['discount_rate'])
        ? (float) $_POST['discount_rate']
        : null;

    $shape_type = isset($_POST['shape_type'])
        ? sanitize_text_field(wp_unslash($_POST['shape_type']))
        : '';

    $user_agent = isset($_SERVER['HTTP_USER_AGENT'])
        ? sanitize_textarea_field(wp_unslash($_SERVER['HTTP_USER_AGENT']))
        : '';


    /* --------------------------------------------------------
     * Insert diagnostic record
     * -------------------------------------------------------- */

    $inserted = $wpdb->insert(
        $table_name,
        [
            'incident_reference' => $incident_reference,
            'created_at'         => current_time('mysql'),
            'http_status'        => $http_status,
            'http_status_text'   => $http_status_text,
            'jquery_status'      => $jquery_status,
            'error_thrown'       => $error_thrown,
            'ajax_action'        => $ajax_action,
            'ajax_url'           => $ajax_url,
            'product_id'         => $product_id,
            'width'              => $width,
            'length'             => $length,
            'qty'                => $qty,
            'discount_rate'      => $discount_rate,
            'shape_type'         => $shape_type,
            'user_agent'         => $user_agent,
        ],
        [
            '%s',
            '%s',
            '%d',
            '%s',
            '%s',
            '%s',
            '%s',
            '%s',
            '%d',
            '%f',
            '%f',
            '%d',
            '%f',
            '%s',
            '%s',
        ]
    );


    /* --------------------------------------------------------
     * Return result
     * -------------------------------------------------------- */

    if ($inserted === false) {

        /*
         * Do NOT expose the database error to the customer.
         */
        wp_send_json_error([
            'message' => 'Unable to record diagnostic information.'
        ]);
    }


    wp_send_json_success([
        'recorded' => true
    ]);
}


/* ============================================================
 * 3. REST API DIAGNOSTIC ENDPOINT
 * ============================================================ */

/**
 * Register public REST endpoint for price-generation diagnostics.
 *
 * This endpoint is deliberately separate from admin-ajax.php.
 */
add_action('rest_api_init', 'md_register_price_error_rest_route');

function md_register_price_error_rest_route() {

    register_rest_route(
        'materials-direct/v1',
        '/price-error',
        [
            'methods'             => 'POST',
            'callback'            => 'md_log_price_error_rest_callback',
            'permission_callback' => '__return_true',
        ]
    );
}


/**
 * Record a failed price-generation request.
 *
 * This endpoint does not alter WooCommerce pricing,
 * carts, sessions or orders.
 */
function md_log_price_error_rest_callback(WP_REST_Request $request) {

    global $wpdb;

    $table_name = $wpdb->prefix . 'md_price_diagnostics';


    /* --------------------------------------------------------
     * Get JSON request data
     * -------------------------------------------------------- */

    $data = $request->get_json_params();

    if (!is_array($data)) {
        return new WP_REST_Response(
            [
                'recorded' => false,
                'message'  => 'Invalid diagnostic request.'
            ],
            400
        );
    }


    /* --------------------------------------------------------
     * Incident reference
     * -------------------------------------------------------- */

    $incident_reference = isset($data['incident_reference'])
        ? sanitize_text_field($data['incident_reference'])
        : '';

    if (
        $incident_reference === '' ||
        !preg_match(
            '/^PRICE-[0-9]{14}-[0-9]{4}$/',
            $incident_reference
        )
    ) {
        return new WP_REST_Response(
            [
                'recorded' => false,
                'message'  => 'Invalid incident reference.'
            ],
            400
        );
    }


    /* --------------------------------------------------------
     * Diagnostic values
     * -------------------------------------------------------- */

    $http_status = isset($data['http_status'])
        ? absint($data['http_status'])
        : 0;

    $http_status_text = isset($data['http_status_text'])
        ? sanitize_text_field($data['http_status_text'])
        : '';

    $jquery_status = isset($data['jquery_status'])
        ? sanitize_text_field($data['jquery_status'])
        : '';

    $error_thrown = isset($data['error_thrown'])
        ? sanitize_text_field($data['error_thrown'])
        : '';

    $ajax_action = isset($data['ajax_action'])
        ? sanitize_text_field($data['ajax_action'])
        : '';

    $ajax_url = isset($data['ajax_url'])
        ? esc_url_raw($data['ajax_url'])
        : '';

    $product_id = isset($data['product_id'])
        ? absint($data['product_id'])
        : 0;

    $width = isset($data['width'])
        ? (float) $data['width']
        : null;

    $length = isset($data['length'])
        ? (float) $data['length']
        : null;

    $qty = isset($data['qty'])
        ? absint($data['qty'])
        : 0;

    $discount_rate = isset($data['discount_rate'])
        ? (float) $data['discount_rate']
        : null;

    $shape_type = isset($data['shape_type'])
        ? sanitize_text_field($data['shape_type'])
        : '';

    $user_agent = isset($_SERVER['HTTP_USER_AGENT'])
        ? sanitize_textarea_field(
            wp_unslash($_SERVER['HTTP_USER_AGENT'])
        )
        : '';


    /* --------------------------------------------------------
     * Prevent duplicate incident references
     * -------------------------------------------------------- */

    $existing_id = $wpdb->get_var(
        $wpdb->prepare(
            "SELECT id
             FROM {$table_name}
             WHERE incident_reference = %s
             LIMIT 1",
            $incident_reference
        )
    );

    if ($existing_id) {

        return new WP_REST_Response(
            [
                'recorded' => true,
                'duplicate' => true
            ],
            200
        );
    }


    /* --------------------------------------------------------
     * Insert diagnostic record
     * -------------------------------------------------------- */

    $inserted = $wpdb->insert(
        $table_name,
        [
            'incident_reference' => $incident_reference,
            'created_at'         => current_time('mysql'),
            'http_status'        => $http_status,
            'http_status_text'   => $http_status_text,
            'jquery_status'      => $jquery_status,
            'error_thrown'       => $error_thrown,
            'ajax_action'        => $ajax_action,
            'ajax_url'           => $ajax_url,
            'product_id'         => $product_id,
            'width'              => $width,
            'length'             => $length,
            'qty'                => $qty,
            'discount_rate'      => $discount_rate,
            'shape_type'         => $shape_type,
            'user_agent'         => $user_agent,
        ],
        [
            '%s',
            '%s',
            '%d',
            '%s',
            '%s',
            '%s',
            '%s',
            '%s',
            '%d',
            '%f',
            '%f',
            '%d',
            '%f',
            '%s',
            '%s',
        ]
    );


    /* --------------------------------------------------------
     * Return result
     * -------------------------------------------------------- */

    if ($inserted === false) {

        /*
         * Do not expose the database error.
         */
        return new WP_REST_Response(
            [
                'recorded' => false
            ],
            500
        );
    }


    return new WP_REST_Response(
        [
            'recorded' => true
        ],
        201
    );
}